name: 'Hola mundo App Workflow'
on: 
  push:
    branches:
      - main
      - aprendiendo-github-actions
  pull_request:
    branches:
      - main
      - aprendiendo-github-actions
  paths:
    - 'src/**'
    - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v24
      - name: Run python script
        run: python src/hola_mundo.py
  